version: '3.7'

services:
  devblog-app-service:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=SECRET_KEY
      - ALLOWED_ORIGINS=http://localhost:3000 http://127.0.0.1:3000 http://localhost:8000 http://127.0.0.1:8000 http://localhost
      - ALLOWED_HOSTS=*
      - SQL_HOST=devblog-postgres-service
      - SQL_PORT=5432
      - DATABASE=postgres
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
      - DATABASE_URL=postgresql://username:password@devblog-postgres-service:5432/dbname

  devblog-nginx-service:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - devblog-app-service
  
  devblog-postgres-service:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname

volumes:
  static:
  postgres_data: {}

  