# Generated by Django 4.2.4 on 2023-09-16 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('header_image', models.ImageField(blank=True, upload_to='images/')),
                ('content_fr', models.TextField()),
                ('content_en', models.TextField()),
                ('abstract_fr', models.TextField(max_length=2550)),
                ('abstract_en', models.TextField(max_length=2550)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, height_field=32, upload_to='images/', width_field=32)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('header_image', models.ImageField(blank=True, upload_to='images/')),
                ('content_fr', models.TextField()),
                ('content_en', models.TextField()),
                ('abstract_fr', models.TextField(max_length=2550)),
                ('abstract_en', models.TextField(max_length=2550)),
                ('released_at', models.DateTimeField()),
                ('favicon', models.ImageField(blank=True, height_field=32, upload_to='images/', width_field=32)),
                ('git_repo', models.URLField()),
                ('url', models.URLField()),
                ('tags', models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', to='posts.tag')),
                ('user', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', to='posts.tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
