# Generated by Django 4.2.4 on 2023-09-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_article_tag_website_delete_post_article_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='background_color',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='frontend/public/images/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, upload_to='frontend/public/images/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='frontend/public/images/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='frontend/public/images/'),
        ),
    ]
