# Generated by Django 4.2.4 on 2023-09-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_tag_background_color_alter_article_header_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='text_color',
            field=models.CharField(default='#000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
    ]
