# Generated by Django 4.2.4 on 2023-09-21 06:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_article_header_image_alter_tag_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_fr',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='website',
            name='content_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='website',
            name='content_fr',
            field=tinymce.models.HTMLField(),
        ),
    ]
